INSERT INTO assets (id, symbol, name, type, sector) VALUES
(60, 'NVDA', 'NVIDIA Corporation', 'stock', 'Technology'),
(61, 'AAPL', 'Apple Inc.', 'stock', 'Technology'),
(62, 'MSFT', 'Microsoft Corporation', 'stock', 'Technology'),
(63, 'GOOGL', 'Alphabet Inc.', 'stock', 'Communication Services'),
(64, 'AMZN', 'Amazon.com, Inc.', 'stock', 'Consumer Cyclical'),
(65, 'TSLA', 'Tesla, Inc.', 'stock', 'Consumer Cyclical'),
(66, 'META', 'Meta Platforms, Inc.', 'stock', 'Communication Services'),
(67, 'AMD', 'Advanced Micro Devices, Inc.', 'stock', 'Technology'),
(68, 'INTC', 'Intel Corporation', 'stock', 'Technology'),
(69, 'AVGO', 'Broadcom Inc.', 'stock', 'Technology'),
(70, 'MU', 'Micron Technology, Inc.', 'stock', 'Technology'),
(71, 'PFE', 'Pfizer Inc.', 'stock', 'Healthcare'),
(72, 'SOFI', 'SoFi Technologies, Inc.', 'stock', 'Financial Services'),
(73, 'NOK', 'Nokia Oyj', 'stock', 'Technology'),
(74, 'SPY', 'SPDR S&P 500 ETF Trust', 'stock', 'N/A'),  -- inclus pour ta simu
(75, 'QQQ', 'Invesco QQQ Trust', 'stock', 'N/A'),
(76, 'RSP', 'Invesco S&P 500 Equal Weight ETF', 'stock', 'N/A'),
(77, 'VRT', 'Vertiv Holdings Co', 'stock', 'Industrials'),
(78, 'EQIX', 'Equinix, Inc.', 'stock', 'Real Estate'),
(79, 'CLS', 'Celestica Inc.', 'stock', 'Technology'),
(80, 'ANET', 'Arista Networks, Inc.', 'stock', 'Technology'),
(81, 'LITE', 'Lumentum Holdings Inc.', 'stock', 'Technology'),
(82, 'FIX', 'Comfort Systems USA, Inc.', 'stock', 'Industrials'),
(83, 'WTS', 'Watts Water Technologies, Inc.', 'stock', 'Industrials'),
(84, 'CAT', 'Caterpillar Inc.', 'stock', 'Industrials'),
(85, 'WMT', 'Walmart Inc.', 'stock', 'Consumer Defensive'),
(86, 'JPM', 'JPMorgan Chase & Co.', 'stock', 'Financial Services'),
(87, 'V', 'Visa Inc.', 'stock', 'Financial Services'),
(88, 'MA', 'Mastercard Incorporated', 'stock', 'Financial Services'),
(89, 'BRK-B', 'Berkshire Hathaway Inc.', 'stock', 'Financial Services'),
(90, 'GOOG', 'Alphabet Inc.', 'stock', 'Communication Services'),
(91, 'NFLX', 'Netflix, Inc.', 'stock', 'Communication Services'),
(92, 'ADBE', 'Adobe Inc.', 'stock', 'Technology'),
(93, 'CRM', 'Salesforce, Inc.', 'stock', 'Technology'),
(94, 'ORCL', 'Oracle Corporation', 'stock', 'Technology'),
(95, 'CSCO', 'Cisco Systems, Inc.', 'stock', 'Technology'),
(96, 'IBM', 'International Business Machines Corporation', 'stock', 'Technology'),
(97, 'QCOM', 'QUALCOMM Incorporated', 'stock', 'Technology'),
(98, 'TXN', 'Texas Instruments Incorporated', 'stock', 'Technology'),
(99, 'AMAT', 'Applied Materials, Inc.', 'stock', 'Technology'),
(100, 'NOW', 'ServiceNow, Inc.', 'stock', 'Technology'),
(101, 'PANW', 'Palo Alto Networks, Inc.', 'stock', 'Technology'),
(102, 'CRWD', 'CrowdStrike Holdings, Inc.', 'stock', 'Technology'),
(103, 'SNOW', 'Snowflake Inc.', 'stock', 'Technology'),
(104, 'PLTR', 'Palantir Technologies Inc.', 'stock', 'Technology'),
(105, 'ARM', 'Arm Holdings plc', 'stock', 'Technology'),
(106, 'SMCI', 'Super Micro Computer, Inc.', 'stock', 'Technology'),
(107, 'DELL', 'Dell Technologies Inc.', 'stock', 'Technology'),
(108, 'HPQ', 'HP Inc.', 'stock', 'Technology'),
(109, 'HPE', 'Hewlett Packard Enterprise Company', 'stock', 'Technology'),
(110, 'MRVL', 'Marvell Technology, Inc.', 'stock', 'Technology'),
(111, 'KLAC', 'KLA Corporation', 'stock', 'Technology'),
(112, 'LRCX', 'Lam Research Corporation', 'stock', 'Technology'),
(113, 'ASML', 'ASML Holding N.V.', 'stock', 'Technology'),
(114, 'T', 'AT&T Inc.', 'stock', 'Communication Services'),
(115, 'VZ', 'Verizon Communications Inc.', 'stock', 'Communication Services'),
(116, 'CMCSA', 'Comcast Corporation', 'stock', 'Communication Services'),
(117, 'DIS', 'The Walt Disney Company', 'stock', 'Communication Services'),
(118, 'NKE', 'NIKE, Inc.', 'stock', 'Consumer Cyclical'),
(119, 'MCD', 'McDonald''s Corporation', 'stock', 'Consumer Cyclical'),
(120, 'SBUX', 'Starbucks Corporation', 'stock', 'Consumer Cyclical'),
(121, 'KO', 'The Coca-Cola Company', 'stock', 'Consumer Defensive'),
(122, 'PEP', 'PepsiCo, Inc.', 'stock', 'Consumer Defensive'),
(123, 'PG', 'The Procter & Gamble Company', 'stock', 'Consumer Defensive'),
(124, 'JNJ', 'Johnson & Johnson', 'stock', 'Healthcare'),
(125, 'ABBV', 'AbbVie Inc.', 'stock', 'Healthcare'),
(126, 'MRK', 'Merck & Co., Inc.', 'stock', 'Healthcare'),
(127, 'LLY', 'Eli Lilly and Company', 'stock', 'Healthcare'),
(128, 'UNH', 'UnitedHealth Group Incorporated', 'stock', 'Healthcare'),
(129, 'XOM', 'Exxon Mobil Corporation', 'stock', 'Energy'),
(130, 'CVX', 'Chevron Corporation', 'stock', 'Energy'),
(131, 'BA', 'The Boeing Company', 'stock', 'Industrials'),
(132, 'GE', 'General Electric Company', 'stock', 'Industrials'),
(133, 'HON', 'Honeywell International Inc.', 'stock', 'Industrials'),
(134, 'UNP', 'Union Pacific Corporation', 'stock', 'Industrials'),
(135, 'UPS', 'United Parcel Service, Inc.', 'stock', 'Industrials'),
(136, 'AAL', 'American Airlines Group Inc.', 'stock', 'Industrials'),
(137, 'DAL', 'Delta Air Lines, Inc.', 'stock', 'Industrials'),
(138, 'MARA', 'MARA Holdings, Inc.', 'stock', 'Financial Services'),
(139, 'COIN', 'Coinbase Global, Inc.', 'stock', 'Financial Services'),
(140, 'HOOD', 'Robinhood Markets, Inc.', 'stock', 'Financial Services'),
(141, 'RKLB', 'Rocket Lab USA, Inc.', 'stock', 'Industrials'),
(142, 'SYM', 'Symbotic Inc.', 'stock', 'Industrials'),
(143, 'INOD', 'Innodata Inc.', 'stock', 'Technology'),
(144, 'CAMT', 'Camtek Ltd.', 'stock', 'Technology'),
(145, 'AMKR', 'Amkor Technology, Inc.', 'stock', 'Technology'),
(146, 'CIEN', 'Ciena Corporation', 'stock', 'Technology'),
(147, 'GLW', 'Corning Incorporated', 'stock', 'Technology'),
(148, 'STX', 'Seagate Technology Holdings plc', 'stock', 'Technology'),
(149, 'WDC', 'Western Digital Corporation', 'stock', 'Technology'),
(150, 'TER', 'Teradyne, Inc.', 'stock', 'Technology'),
(151, 'STR L', 'Sterling Infrastructure, Inc.', 'stock', 'Industrials'),
(152, 'D', 'Dominion Energy, Inc.', 'stock', 'Utilities'),
(153, 'AA', 'Alcoa Corporation', 'stock', 'Basic Materials'),
(154, 'BKNG', 'Booking Holdings Inc.', 'stock', 'Consumer Cyclical'),
(155, 'EA', 'Electronic Arts Inc.', 'stock', 'Communication Services'),
(156, 'BKR', 'Baker Hughes Company', 'stock', 'Energy'),
(157, 'ALNY', 'Alnylam Pharmaceuticals, Inc.', 'stock', 'Healthcare'),
(158, 'ADP', 'Automatic Data Processing, Inc.', 'stock', 'Industrials'),
(159, 'ADSK', 'Autodesk, Inc.', 'stock', 'Technology'),
(160, 'AEP', 'American Electric Power Company, Inc.', 'stock', 'Utilities'),
(161, 'ABNB', 'Airbnb, Inc.', 'stock', 'Consumer Cyclical'),
(162, 'PYPL', 'PayPal Holdings, Inc.', 'stock', 'Financial Services'),
(163, 'UBER', 'Uber Technologies, Inc.', 'stock', 'Consumer Cyclical'),
(164, 'LYFT', 'Lyft, Inc.', 'stock', 'Consumer Cyclical'),
(165, 'ZM', 'Zoom Video Communications, Inc.', 'stock', 'Technology'),
(166, 'DOCU', 'DocuSign, Inc.', 'stock', 'Technology'),
(167, 'TEAM', 'Atlassian Corporation', 'stock', 'Technology'),
(168, 'DDOG', 'Datadog, Inc.', 'stock', 'Technology'),
(169, 'MDB', 'MongoDB, Inc.', 'stock', 'Technology'),
(170, 'CRSP', 'CRISPR Therapeutics AG', 'stock', 'Healthcare'),
(171, 'RXRX', 'Recursion Pharmaceuticals, Inc.', 'stock', 'Healthcare'),
(172, 'PATH', 'UiPath Inc.', 'stock', 'Technology'),
(173, 'SOUN', 'SoundHound AI, Inc.', 'stock', 'Technology'),
(174, 'UPST', 'Upstart Holdings, Inc.', 'stock', 'Financial Services'),
(175, 'CVNA', 'Carvana Co.', 'stock', 'Consumer Cyclical'),
(176, 'DKNG', 'DraftKings Inc.', 'stock', 'Consumer Cyclical'),
(177, 'RBLX', 'Roblox Corporation', 'stock', 'Communication Services'),
(178, 'U', 'Unity Software Inc.', 'stock', 'Technology'),
(179, 'TTD', 'The Trade Desk, Inc.', 'stock', 'Technology'),
(180, 'MELI', 'MercadoLibre, Inc.', 'stock', 'Consumer Cyclical'),
(181, 'SHOP', 'Shopify Inc.', 'stock', 'Consumer Cyclical'),
(182, 'SE', 'Sea Limited', 'stock', 'Consumer Cyclical'),
(183, 'PDD', 'PDD Holdings Inc.', 'stock', 'Consumer Cyclical'),
(184, 'BABA', 'Alibaba Group Holding Limited', 'stock', 'Consumer Cyclical'),
(185, 'JD', 'JD.com, Inc.', 'stock', 'Consumer Cyclical'),
(186, 'BIDU', 'Baidu, Inc.', 'stock', 'Communication Services'),
(187, 'NET', 'Cloudflare, Inc.', 'stock', 'Technology'),
(188, 'ZS', 'Zscaler, Inc.', 'stock', 'Technology'),
(189, 'FTNT', 'Fortinet, Inc.', 'stock', 'Technology'),
(190, 'NXPI', 'NXP Semiconductors N.V.', 'stock', 'Technology'),
(191, 'MCHP', 'Microchip Technology Incorporated', 'stock', 'Technology'),
(192, 'ON', 'ON Semiconductor Corporation', 'stock', 'Technology'),
(193, 'MPWR', 'Monolithic Power Systems, Inc.', 'stock', 'Technology'),
(194, 'ENTG', 'Entegris, Inc.', 'stock', 'Technology'),
(195, 'KLAC', 'KLA Corporation', 'stock', 'Technology'),  -- doublon évité plus haut
(196, 'CDNS', 'Cadence Design Systems, Inc.', 'stock', 'Technology'),
(197, 'SNPS', 'Synopsys, Inc.', 'stock', 'Technology'),
(198, 'WDAY', 'Workday, Inc.', 'stock', 'Technology'),
(199, 'ROP', 'Roper Technologies, Inc.', 'stock', 'Industrials'),
(200, 'GWW', 'W.W. Grainger, Inc.', 'stock', 'Industrials'),
(201, 'FAST', 'Fastenal Company', 'stock', 'Industrials'),
(202, 'ODFL', 'Old Dominion Freight Line, Inc.', 'stock', 'Industrials'),
(203, 'CSX', 'CSX Corporation', 'stock', 'Industrials'),
(204, 'NSC', 'Norfolk Southern Corporation', 'stock', 'Industrials'),
(205, 'FDX', 'FedEx Corporation', 'stock', 'Industrials'),
(206, 'EMR', 'Emerson Electric Co.', 'stock', 'Industrials'),
(207, 'ITW', 'Illinois Tool Works Inc.', 'stock', 'Industrials'),
(208, 'PH', 'Parker-Hannifin Corporation', 'stock', 'Industrials'),
(209, 'MMM', '3M Company', 'stock', 'Industrials'),
(210, 'AAPL', 'Apple Inc.', 'Technology', 'core'),
(211, 'MSFT', 'Microsoft Corporation', 'Technology', 'core'),
(212, 'GOOGL', 'Alphabet Inc.', 'Communication Services', 'core'),
(213, 'GOOG', 'Alphabet Inc.', 'Communication Services', 'core'),
(214, 'AMZN', 'Amazon.com Inc.', 'Consumer Cyclical', 'core'),
(215, 'NVDA', 'NVIDIA Corporation', 'Technology', 'core'),
(216, 'META', 'Meta Platforms Inc.', 'Communication Services', 'core'),
(217, 'TSLA', 'Tesla Inc.', 'Consumer Cyclical', 'core'),
(218, 'AVGO', 'Broadcom Inc.', 'Technology', 'core'),
(219, 'BRK.B', 'Berkshire Hathaway Inc.', 'Financial Services', 'core'),
(220, 'LLY', 'Eli Lilly and Company', 'Healthcare', 'core'),
(221, 'JPM', 'JPMorgan Chase & Co.', 'Financial Services', 'core'),
(222, 'V', 'Visa Inc.', 'Financial Services', 'core'),
(223, 'MA', 'Mastercard Inc.', 'Financial Services', 'core'),
(224, 'UNH', 'UnitedHealth Group Inc.', 'Healthcare', 'core'),
(225, 'XOM', 'Exxon Mobil Corporation', 'Energy', 'core'),
(226, 'JNJ', 'Johnson & Johnson', 'Healthcare', 'core'),
(227, 'PG', 'Procter & Gamble Co.', 'Consumer Defensive', 'core'),
(228, 'HD', 'Home Depot Inc.', 'Consumer Cyclical', 'core'),
(229, 'MRK', 'Merck & Co. Inc.', 'Healthcare', 'core'),
(230, 'COST', 'Costco Wholesale Corp.', 'Consumer Defensive', 'core'),
(231, 'ABBV', 'AbbVie Inc.', 'Healthcare', 'core'),
(232, 'ADBE', 'Adobe Inc.', 'Technology', 'core'),
(233, 'CRM', 'Salesforce Inc.', 'Technology', 'core'),
(234, 'NFLX', 'Netflix Inc.', 'Communication Services', 'core'),
(235, 'AMD', 'Advanced Micro Devices Inc.', 'Technology', 'core'),
(236, 'TMUS', 'T-Mobile US Inc.', 'Communication Services', 'core'),
(237, 'QCOM', 'QUALCOMM Inc.', 'Technology', 'core'),
(238, 'CSCO', 'Cisco Systems Inc.', 'Technology', 'core'),
(239, 'PEP', 'PepsiCo Inc.', 'Consumer Defensive', 'core'),
(240, 'KO', 'Coca-Cola Co.', 'Consumer Defensive', 'core'),
(241, 'ORCL', 'Oracle Corporation', 'Technology', 'core'),
(242, 'LIN', 'Linde plc', 'Basic Materials', 'core'),
(243, 'ACN', 'Accenture plc', 'Technology', 'core'),
(244, 'MCD', 'McDonald’s Corporation', 'Consumer Cyclical', 'core'),
(245, 'ABT', 'Abbott Laboratories', 'Healthcare', 'core'),
(246, 'WMT', 'Walmart Inc.', 'Consumer Defensive', 'core'),
(247, 'DIS', 'Walt Disney Co.', 'Communication Services', 'core'),
(248, 'NEE', 'NextEra Energy Inc.', 'Utilities', 'core'),
(249, 'TXN', 'Texas Instruments Inc.', 'Technology', 'core'),
(250, 'AMGN', 'Amgen Inc.', 'Healthcare', 'core'),
(251, 'HON', 'Honeywell International Inc.', 'Industrials', 'core'),
(252, 'UNP', 'Union Pacific Corporation', 'Industrials', 'core'),
(253, 'SPGI', 'S&P Global Inc.', 'Financial Services', 'core'),
(254, 'AXP', 'American Express Co.', 'Financial Services', 'core'),
(255, 'PFE', 'Pfizer Inc.', 'Healthcare', 'core'),
(256, 'LOW', 'Lowe’s Companies Inc.', 'Consumer Cyclical', 'core'),
(257, 'BKNG', 'Booking Holdings Inc.', 'Consumer Cyclical', 'core'),
(258, 'GS', 'Goldman Sachs Group Inc.', 'Financial Services', 'core'),
(259, 'CAT', 'Caterpillar Inc.', 'Industrials', 'core'),
(260, 'MS', 'Morgan Stanley', 'Financial Services', 'core'),
(261, 'BLK', 'BlackRock Inc.', 'Financial Services', 'core'),
(262, 'SCHW', 'Charles Schwab Corp.', 'Financial Services', 'core'),
(263, 'MDT', 'Medtronic plc', 'Healthcare', 'core'),
(264, 'PLD', 'Prologis Inc.', 'Real Estate', 'core'),
(265, 'SBUX', 'Starbucks Corporation', 'Consumer Cyclical', 'core'),
(266, 'INTU', 'Intuit Inc.', 'Technology', 'core'),
(267, 'GE', 'General Electric Company', 'Industrials', 'core'),
(268, 'AMAT', 'Applied Materials Inc.', 'Technology', 'core'),
(269, 'T', 'AT&T Inc.', 'Communication Services', 'core'),
(270, 'NOW', 'ServiceNow Inc.', 'Technology', 'core'),
(271, 'SYK', 'Stryker Corporation', 'Healthcare', 'core'),
(272, 'VZ', 'Verizon Communications Inc.', 'Communication Services', 'core'),
(273, 'ISRG', 'Intuitive Surgical Inc.', 'Healthcare', 'core'),
(274, 'ELV', 'Elevance Health Inc.', 'Healthcare', 'core'),
(275, 'REGN', 'Regeneron Pharmaceuticals Inc.', 'Healthcare', 'core'),
(276, 'MU', 'Micron Technology Inc.', 'Technology', 'core'),
(277, 'KLAC', 'KLA Corporation', 'Technology', 'core'),
(278, 'ADP', 'Automatic Data Processing Inc.', 'Industrials', 'core'),
(279, 'BA', 'Boeing Company', 'Industrials', 'core'),
(280, 'GILD', 'Gilead Sciences Inc.', 'Healthcare', 'core'),
(281, 'ZTS', 'Zoetis Inc.', 'Healthcare', 'core'),
(282, 'CI', 'Cigna Corporation', 'Healthcare', 'core'),
(283, 'FI', 'Fiserv Inc.', 'Technology', 'core'),
(284, 'DE', 'Deere & Company', 'Industrials', 'core'),
(285, 'BMY', 'Bristol-Myers Squibb Co.', 'Healthcare', 'core'),
(286, 'SO', 'Southern Company', 'Utilities', 'core'),
(287, 'DHR', 'Danaher Corporation', 'Healthcare', 'core'),
(288, 'ETN', 'Eaton Corporation plc', 'Industrials', 'core'),
(289, 'LRCX', 'Lam Research Corporation', 'Technology', 'core'),
(290, 'WDC', 'Western Digital Corporation', 'Technology', 'core'),
(291, 'FIX', 'Comfort Systems USA Inc.', 'Industrials', 'core'),
(292, 'STX', 'Seagate Technology Holdings plc', 'Technology', 'core'),
(293, 'CIEN', 'Ciena Corporation', 'Technology', 'core'),

-- ==================== NICHE (≈ 100) ====================
(294, 'PLTR', 'Palantir Technologies Inc.', 'Technology', 'niche'),
(295, 'SOFI', 'SoFi Technologies Inc.', 'Financial Services', 'niche'),
(296, 'RKLB', 'Rocket Lab USA Inc.', 'Industrials', 'niche'),
(297, 'ARM', 'Arm Holdings plc', 'Technology', 'niche'),
(298, 'CRWD', 'CrowdStrike Holdings Inc.', 'Technology', 'niche'),
(299, 'SNOW', 'Snowflake Inc.', 'Technology', 'niche'),
(300, 'WTS', 'Watts Water Technologies Inc.', 'Industrials', 'niche'),
(301, 'NIO', 'NIO Inc.', 'Consumer Cyclical', 'niche'),
(302, 'RIVN', 'Rivian Automotive Inc.', 'Consumer Cyclical', 'niche'),
(303, 'PATH', 'UiPath Inc.', 'Technology', 'niche'),
(304, 'UPST', 'Upstart Holdings Inc.', 'Financial Services', 'niche'),
(305, 'COIN', 'Coinbase Global Inc.', 'Financial Services', 'niche'),
(306, 'HOOD', 'Robinhood Markets Inc.', 'Financial Services', 'niche'),
(307, 'AFRM', 'Affirm Holdings Inc.', 'Financial Services', 'niche'),
(308, 'SQ', 'Block Inc.', 'Technology', 'niche'),
(309, 'SHOP', 'Shopify Inc.', 'Consumer Cyclical', 'niche'),
(310, 'DDOG', 'Datadog Inc.', 'Technology', 'niche'),
(311, 'NET', 'Cloudflare Inc.', 'Technology', 'niche'),
(312, 'HUBS', 'HubSpot Inc.', 'Technology', 'niche'),
(313, 'MDB', 'MongoDB Inc.', 'Technology', 'niche'),
(314, 'OKTA', 'Okta Inc.', 'Technology', 'niche'),
(315, 'ZS', 'Zscaler Inc.', 'Technology', 'niche'),
(316, 'PANW', 'Palo Alto Networks Inc.', 'Technology', 'niche'),
(317, 'FTNT', 'Fortinet Inc.', 'Technology', 'niche'),
(318, 'ANET', 'Arista Networks Inc.', 'Technology', 'niche'),
(319, 'SMCI', 'Super Micro Computer Inc.', 'Technology', 'niche'),
(320, 'VRT', 'Vertiv Holdings Co.', 'Industrials', 'niche'),
(321, 'CLS', 'Celestica Inc.', 'Technology', 'niche'),
(322, 'APP', 'AppLovin Corporation', 'Technology', 'niche'),
(323, 'INTC', 'Intel Corporation', 'Technology', 'niche'),
(324, 'MU', 'Micron Technology Inc.', 'Technology', 'niche'),
(325, 'AMD', 'Advanced Micro Devices Inc.', 'Technology', 'niche'),
(326, 'NOK', 'Nokia Corporation', 'Technology', 'niche'),
(327, 'GV', 'Visionary Holdings Inc.', 'Industrials', 'niche'),
(328, 'AIXI', 'Xiao-I Corporation', 'Technology', 'niche'),
(329, 'SKYQ', 'Sky Quarry Inc.', 'Basic Materials', 'niche'),
(330, 'COCP', 'Cocrystal Pharma Inc.', 'Healthcare', 'niche'),
(331, 'BDRX', 'Biodexa Pharmaceuticals Plc', 'Healthcare', 'niche'),
(332, 'PLUG', 'Plug Power Inc.', 'Industrials', 'niche'),
(333, 'LCID', 'Lucid Group Inc.', 'Consumer Cyclical', 'niche'),
(334, 'BITO', 'ProShares Bitcoin Strategy ETF', 'Financial Services', 'niche'),
(335, 'TQQQ', 'ProShares UltraPro QQQ', 'Financial Services', 'niche'),
(336, 'SOXL', 'Direxion Daily Semiconductor Bull 3X', 'Financial Services', 'niche'),
(337, 'SQQQ', 'ProShares UltraPro Short QQQ', 'Financial Services', 'niche'),
(338, 'TSLL', 'Direxion Daily TSLA Bull 2X', 'Financial Services', 'niche'),
(339, 'TER', 'Teradyne Inc.', 'Technology', 'niche'),
(340, 'GLW', 'Corning Inc.', 'Technology', 'niche'),
(341, 'MRNA', 'Moderna Inc.', 'Healthcare', 'niche'),
(342, 'GNRC', 'Generac Holdings Inc.', 'Industrials', 'niche'),
(343, 'TPL', 'Texas Pacific Land Corp.', 'Energy', 'niche')
ON CONFLICT (symbol) DO NOTHING;
